/* vim:set noexpandtab tabstop=4 wrap filetype=cpp */
#ifndef PlotNeutronCaptures_H
#define PlotNeutronCaptures_H

#include <string>
#include <iostream>

#include "Tool.h"
#include "MTreeReader.h"

class TFile;

/**
* \class PlotNeutronCaptures
*
* This tool makes plots from the files generated by the TruthNeutronCaptures or TrueNCaptures tools, to characterise neutron captures
*
* $Author: M.O'Flahery $
* $Date: 2020/08/12 $
* Contact: marcus.o-flaherty@warwick.ac.uk
*/
class PlotNeutronCaptures: public Tool {
	
	public:
	PlotNeutronCaptures(); ///< Simple constructor
	bool Initialise(std::string configfile,DataModel &data); ///< Initialise Function for setting up Tool resorces. @param configfile The path and name of the dynamic configuration file to read in. @param data A reference to the transient data class used to pass information between Tools.
	bool Execute();        ///< Executre function used to perform Tool perpose. 
	bool Finalise();       ///< Finalise funciton used to clean up resorces.
	
	private:
	// functions
	// =========
	int GetBranches();
	int MakeHistos();
	
	// tool variables
	// ==============
	std::string outputFile;
	TFile* outfile=nullptr;
	TTree* inTree=nullptr;
	TTree* friendTree=nullptr;
	
	std::string logmessage="";
	
};


#endif
